const jobs = [
  {
    position: "Clinical Specialist",
    company: "Gevee",
    location: "Wujiashan",
    status: "Interview",
    type: "Part-Time",
    date: "2023-07-07",
  },
  {
    position: "Sales Manager",
    company: "Zephyr Solutions",
    location: "Lakeside",
    status: "Pending",
    type: "Full-Time",
    date: "2023-09-28",
  },
  {
    position: "Marketing Coordinator",
    company: "BrightMind Agency",
    location: "City Center",
    status: "Declined",
    type: "Full-Time",
    date: "2023-12-18",
  },
  {
    position: "Software Engineer",
    company: "TechLinx Innovations",
    location: "Tech Hub Plaza",
    status: "Interview",
    type: "Full-Time",
    date: "2023-11-10",
  },
  {
    position: "Graphic Designer",
    company: "Artistry Works",
    location: "Creative Park",
    status: "Pending",
    type: "Internship",
    date: "2023-05-24",
  },
  {
    position: "Financial Analyst",
    company: "InvestEdge",
    location: "Financial District",
    status: "Interview",
    type: "Internship",
    date: "2024-04-08",
  },
  {
    position: "Customer Support Specialist",
    company: "HelpHub Solutions",
    location: "Skyline Towers",
    status: "Declined",
    type: "Part-Time",
    date: "2024-01-26",
  },
  {
    position: "HR Manager",
    company: "TalentQuest Inc.",
    location: "Metroplex",
    status: "Pending",
    type: "Full-Time",
    date: "2023-05-11",
  },
  {
    position: "Operations Supervisor",
    company: "Swift Logistics",
    location: "Harbor View",
    status: "Interview",
    type: "Full-Time",
    date: "2024-04-05",
  },
  {
    position: "Research Assistant",
    company: "SciTech Labs",
    location: "Innovation Center",
    status: "Declined",
    type: "Part-Time",
    date: "2023-08-13",
  },
  {
    position: "Software Engineer",
    company: "Tech Innovations Inc.",
    location: "Tech Hub",
    status: "Interview",
    type: "Full-Time",
    date: "2023-09-25",
  },
  {
    position: "Marketing Specialist",
    company: "Digital Marketing Solutions",
    location: "Marketing Center",
    status: "Pending",
    type: "Full-Time",
    date: "2023-10-12",
  },
  {
    position: "Research Intern",
    company: "BioTech Research Institute",
    location: "Science Park",
    status: "Declined",
    type: "Internship",
    date: "2023-08-18",
  },
  {
    position: "Data Analyst",
    company: "Analytics Plus",
    location: "Data Center",
    status: "Interview",
    type: "Full-Time",
    date: "2023-09-05",
  },
  {
    position: "Graphic Designer",
    company: "Creative Solutions Studio",
    location: "Design Hub",
    status: "Pending",
    type: "Part-Time",
    date: "2023-08-30",
  },
  {
    position: "Lab Technician",
    company: "Genomics Innovations Lab",
    location: "Research Facility",
    status: "Interview",
    type: "Full-Time",
    date: "2023-10-10",
  },
  {
    position: "HR Assistant",
    company: "Human Resources Inc.",
    location: "HR Department",
    status: "Pending",
    type: "Part-Time",
    date: "2023-09-15",
  },
  {
    position: "Financial Analyst",
    company: "Finance Solutions Group",
    location: "Financial District",
    status: "Declined",
    type: "Full-Time",
    date: "2023-07-22",
  },
  {
    position: "Software Development Intern",
    company: "Software Tech Solutions",
    location: "Tech Park",
    status: "Pending",
    type: "Internship",
    date: "2023-08-08",
  },
  {
    position: "Customer Service Representative",
    company: "Service Excellence Inc.",
    location: "Customer Support Center",
    status: "Declined",
    type: "Part-Time",
    date: "2023-09-02",
  },
];

export default jobs;